### ISSUE TITLE
ImportError: cannot import name 'BrowshotClient'

### ISSUE THREAD

**Issue by cotton-more** [juliensobrier/browshot-python#1]
After installing browshot package with the command `pip install -U simplejson browshot` and running script got an error

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from browshot import BrowshotClient
ImportError: cannot import name 'BrowshotClient'
```

The `test.py` has only one line of code

``` python
from browshot import BrowshotClient
```

Running importing from a command line shows that there is no an attribute BrowshotClient in browshot module

```
>>> import browshot
>>> dir(browshot)
['__doc__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
```

**Comment by edpark** [comment]
+1 on this issue, I'm having the same problem. Can anyone from Browshot help?

**Comment by juliensobrier** [comment]
Do you know what version of the Browshot library do you have?

**Comment by edpark** [comment]
Hi, it was the latest version 1.14.0.

**Comment by juliensobrier** [comment]
The latest version is actually 1.16: https://pypi.python.org/pypi/Browshot/1.16.0

Can you try to update the library with pip?

**Comment by yumio** [comment]
just FYI - I had this problem when I was trying to use the 1.16 download
via Github and installing it manually.  It worked fine once I just used pip
to install 1.14 (which is the version you have on pypi)

1.14 works just fine.

**Comment by juliensobrier** [comment]
You should get the version 1.16 from pypi, not 1.14.

**Comment by alltheoptions** [comment]
@juliensobrier same error with 1.16 ?

**Comment by juliensobrier** [comment]
I have updated version 1.21.1 in PyPi to fix the issue.
